name: CI CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "17.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Test
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Upload android APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Android-Release
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    runs-on: macos-latest

    steps:
      - name: CheckOut Code
        uses: actions.checkout@v2

      - name: SetUP Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Dependencies
        run: flutter pub get
             sudo gem install cocoapods

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign

      - name: List files in iOS build directory
        run: ls -al build/ios/iphoneos/

      - name: Upload IPS as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: iOS-Release
          path: build/ios/iphoneos/Runner.app.ipa
          if-no-files-found: warn
          include-hidden-files: false